datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost/postgres?currentSchema=recipient`}
    username: ${JDBC_USER:`postgres`}
    password: ${JDBC_PASSWORD:`postgres`}
    driverClassName: 'org.postgresql.Driver'
    maximumPoolSize: 3
logger:
  levels:
    io.github.opendonationassistant: INFO
